### ISSUE TITLE
Sys.win32 reporting false on 32bit cross-compiler

### ISSUE THREAD

**Issue by toots** [ocaml-cross/opam-cross-windows#169]
Test:
```ocaml
let () =
  Printf.printf "Win32: %b\nOs_type: %s\n%!" Sys.win32 Sys.os_type
```

Result:
```shell
Win32: false
Os_type: Win32
```

**Comment by pirbo** [comment]
So...
in `stdlib/sys.mlp`, Sys.win32 is defined as `external win32 : unit -> bool = "%ostype_win32"`.

As far as I understand, the compiler recognize `%ostype_win32` and turns it into `Primitive ((Pctconst Ostype_win32), 1)` (in `bytecomp/translprim.ml` ???? But why is it done in native compilation too then?) Anyway...

Then,
- the bytecode compiler translates this primitive back into calling the c function `caml_sys_const_ostype_win32(value unit)` which is  `Val_bool(0 == strcmp(OCAML_OS_TYPE,"Win32"))` as we want BUT
- the native compiler optimizes this out (I'm not sure where of middle_end/simplify_primitives.ml, asmcomp/closure.ml or asmcomp/cmmgen.ml) into `const_of_bool (Sys.os_type = "Win32")`(or equivalent) and, as I already explained in several places including #122, because of the way cross compilation is achieve (we do basically `linux-pc-ocamlrun mingw-w64-ocamlc` to call the compiler), `Sys.os_type` "of the compiler" is the host os_type and not the target one!

Now the question becomes, why does it work in 64bits? :-D

**Comment by toots** [comment]
The plot thickens! Thanks for investigating.. Could this have to do with the fact that the 32 bit compiler is actually a 32 bit compiler inside a 64 bit host?

**Comment by toots** [comment]
I'm having the same problem with a recent build of ocaml-windows on 64 bit now.. I think I'll have to revert back to the old patches.
