### ISSUE TITLE
Supporting ocaml 4.12

### ISSUE THREAD

**Issue by SteveBronder** [ocaml-cross/opam-cross-windows#195]
Hello! The main `lsp-server` used for giving type information in editors only works with ocaml 4.12, but we need to cross compile for windows so can't upgrade. It would be very nice if `opam-cross-windows` supported 4.12 as that would let us update everything

**Comment by toots** [comment]
I would love to but this depends on available time. Do you want to have a try at it yourself? Happy to give directions.

**Comment by SteveBronder** [comment]
Sorry I don't have access to a windows computer and idt my ocaml-fu is up to snuff :-(

Def appreciate your time, no worries if this isn't something you can put on your plate atm

**Comment by SteveBronder** [comment]
@toots looking at the commit for adding 4.11.2, is a lot of it just copy/pasting that code into a 4.12 folder? How many of the patches from the 4.11.2 version where just brought in from earlier versions?

https://github.com/ocaml-cross/opam-cross-windows/commit/4948b1761ea511a3ab1f3a3b16bf694c65cab927

Then for running the tests is it just calling `run_tests.sh` in the tests folder?

**Comment by WardBrian** [comment]
It is at least a little bit more complicated than that @SteveBronder - the tests rely on version-specific docker images it seems

**Comment by toots** [comment]
Hey y'all! Sorry I got distracted by hurricane Ida last week.

@SteveBronder is right, the upgrade process usually consists in porting the existing patch to the most recent code base, trying to understand those who are not needed anymore and how to adapt those that fail to apply. The trend these past years has been that less and less of these patches are needed, which is great.

As far as I can tell, the last code/patched issue is around os/platform detection. We are building the compiler on a unix system but we want it to report a windows system and the automated way it is done in the upstream code often gets that wrong. The last investigation about this issue was done in https://github.com/ocaml-cross/opam-cross-windows/issues/169 and we couldn't find a better way to do it back then.

Then, we are using specific, fixed configuration. There, too, it is because the `configure` system does not understand the cross-compiling situation very well so we have to be specific about certain parameters. 

Finally, there are specific build scripts to move files around and call the right makefile target. Here, too, there are specific things, typically, we cannot build `optopt` targets, that is a `ocamlopt.opt` compiler recompiled using the freshly compiled `ocamlopt` one because it is a cross-compiler and also cross-compiling specific path for install.

That's pretty much the gist of it. I'd say, overall, cross-compilation support for windows has become much less hacky over the time. I haven't ported `4.12.0` yet for lack of time but, hopefully, if the trend continues, that shouldn't be too difficult to do and I'd be glad to review/help someone do the porting work.

To run the tests, first you have to rebuild a base docker image this way:
```sh
SYSTEM_TYPE=<x86|x64> OCAML_VERSION=<4.12.0> BUILD_BASE=1 ./tests/run_tests.sh
```
Then, push it to the docker hub repo here: https://hub.docker.com/u/ocamlcross. I'm happy to give access or rebuild/push myself once support for `4.12.0` has been added. 

Then, you can change the default version in the tests and you're good to go!

**Comment by WardBrian** [comment]
Thanks @toots - forgive me if this is a dumb question, but I'm not sure how to build this all locally to see if the patches are good or not (or to get to a point where I can rebuild the docker image). I've started the skeleton of an update here https://github.com/WardBrian/opam-cross-windows/tree/ocaml-4.12/

**Comment by toots** [comment]
> Thanks @toots - forgive me if this is a dumb question, but I'm not sure how to build this all locally to see if the patches are good or not (or to get to a point where I can rebuild the docker image). I've started the skeleton of an update here https://github.com/WardBrian/opam-cross-windows/tree/ocaml-4.12/

Great!

Frankly, I'm not sure how I did it last time. Chances are, I probably was doing it straight from inside the docker container.

**Comment by WardBrian** [comment]
I suspect I'm not familiar enough with docker to make too much progress here, the error messages leave a lot to be desired:

```
$ SYSTEM_TYPE=x64 OCAML_VERSION=4.12.0 BUILD_BASE=1 ./tests/run_tests.sh
Building ocamlcross/windows-x64-base:4.12.0.. The command '/bin/sh -c if [ "$SYSTEM" = "x64" ]; then       export TOOLPREF64=/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static- &&       eval $(opam env) && opam update &&       opam install -y -v ocaml-windows ocaml-windows64;     fi' returned a non-zero code: 31
[failed]🚫 
Building ocamlcross/windows-x64-pretest:4.12.0..manifest for ocamlcross/windows-x64-base:4.12.0 not found: manifest unknown: manifest unknown
[failed]🚫🚫 

From github.com:WardBrian/opam-cross-windows
 * branch            master     -> FETCH_HEAD

Building ocaml-windows32.4.12.0.. [skipped]⚠️
Building ocaml-windows.4.12.0.. [skipped]⚠️
Building ocaml-windows64.4.12.0.. [skipped]⚠️

```

**Comment by toots** [comment]
@WardBrian You can start by building locally and then see about switching to docker.

To build locally, I believe you can simple add your local repository to your `opam` setup, something like this:
```
opam repository add windows-dev /path/to/ocaml-cross-windows
```
Then you can `opam update` each time you want to test the package.

**Comment by WardBrian** [comment]
That has been working, thanks! I've fixed the patch but now I'm getting an issue I'm not sure how to fix:

<details open>
<summary>Error</summary>

```
The following actions will be performed:
  ∗ install ocaml-windows64 4.12.0 [required by ocaml-windows]
  ∗ install ocaml-windows   4.12.0
===== ∗ 2 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-windows64.4.12.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocaml-windows64 failed at "/home/brian/.opam/opam-init/hooks/sandbox.sh build /bin/sh ./build.sh x86_64-w64-mingw32".

#=== ERROR while compiling ocaml-windows64.4.12.0 =============================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | git+file:///home/brian/Dev/ml/opam-cross-windows
# path                 ~/.opam/win/.opam-switch/build/ocaml-windows64.4.12.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build /bin/sh ./build.sh x86_64-w64-mingw32
# exit-code            2
# env-file             ~/.opam/log/ocaml-windows64-164409-e0ba4f.env
# output-file          ~/.opam/log/ocaml-windows64-164409-e0ba4f.out
### output ###
# x86_64-w64-mingw32-gcc -c -O2 -mms-bitfields -fno-strict-aliasing -Wall -fno-tree-vrp -g    -DCAML_NAME_SPACE -DUNICODE -D_UNICODE -DWINDOWS_UNICODE=1 -I../../runtime -I../unix  \
# [...]
# ocamlrun ../../tools/ocamlmklib -oc unix accept.o bind.o channels.o close.o close_on.o connect.o createprocess.o dup.o dup2.o errmsg.o envir.o getpeername.o getpid.o getsockname.o gettimeofday.o isatty.o link.o listen.o lockf.o lseek.o nonblock.o mmap.o open.o pipe.o read.o readlink.o rename.o select.o sendrecv.o shutdown.o sleep.o socket.o sockopt.o startup.o stat.o symlink.o system.o times.[...]
# cannot find file '../../tools/ocamlmklib'
# make[4]: *** [../Makefile.otherlibs.common:91: libunix.a] Error 127
# make[4]: Leaving directory '/home/brian/.opam/win/.opam-switch/build/ocaml-windows64.4.12.0/otherlibs/win32unix'
# make[3]: *** [Makefile:34: all] Error 2
# make[3]: Leaving directory '/home/brian/.opam/win/.opam-switch/build/ocaml-windows64.4.12.0/otherlibs'
# make[2]: *** [Makefile:892: otherlibraries] Error 2
# make[2]: Leaving directory '/home/brian/.opam/win/.opam-switch/build/ocaml-windows64.4.12.0'
# make[1]: *** [Makefile:252: all] Error 2
# make[1]: Leaving directory '/home/brian/.opam/win/.opam-switch/build/ocaml-windows64.4.12.0'
# make: *** [Makefile:269: world] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-windows64 4.12.0
└─ 
╶─ No changes have been performed

```
</details>

I'm confused mainly because it doesn't seem like ocamlmklib or the Makefiles which handle it really changed in 4.12, so I'm concerned I've just got something set up wrong.
